site_name: nclpy

site_url: https://HJRubin.github.io/nclpy

repo_url: https://github.com/HJRubin/nclpy

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
         - navigation.expand
         - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          execute: False
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# google_analytics:
#     - UA-XXXXXXXXX-X
#     - auto

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Report Issues: https://github.com/giswqs/nclpy/issues
    - API Reference:
          - nclpy module: nclpy.md
          - utils module: utils.md
          - common module: common.md
          - toolbar module: toolbar.md
          - basemaps module: basemaps.md
          - generate point module: generate_points.md
    - Notebooks:
          - notebooks/ipyleaflet_intro.ipynb 
          - notebooks/folium_intro.ipynb
          - notebooks/nclpy_intro.ipynb
          - notebooks/add_shapefile.ipynb
          - notebooks/test_utils.ipynb
          - notebooks/earthengine_intro.ipynb
          - notebooks/ipywidgets.ipynb
          - notebooks/ipywidgets_box.ipynb
          - notebooks/ipywidgets_events.ipynb
          - notebooks/toolbar.ipynb
          - notebooks/ipyfilechooser.ipynb
          - notebooks/geopandas.ipynb
          - notebooks/whitebox.ipynb
          - notebooks/toolbar_gui.ipynb
          - notebooks/generate_points_test.ipynb
          - notebooks/csv_to_shapefile.ipynb